---
deployment:
  tasks:
    - export DEPLOYPATH=/home/penyelam/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
